version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: cryptobolt_nginx
    ports:
      - "8004:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: cryptobolt_mysql
#    restart: unless-stopped
#    tty: true
    ports:
      - "3005:3306"
    environment:
      MYSQL_DATABASE: cryptobolt
      MYSQL_USER: cryptobolt
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: cryptobolt_php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9005:9000"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: cryptobolt_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  #  npm:
  #    image: node:13.7
  #    container_name: condo_npm
  #    volumes:
  #      - ./src:/var/www/html
  #    working_dir: /var/www/html
  #    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: cryptobolt_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
